@SlotMachineSharp.Server_HostAddress = http://localhost:5250

GET {{SlotMachineSharp.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{SlotMachineSharp.Server_HostAddress}}/gamble/
Accept: application/json

###
